pub mod agent_api_keys;
pub mod agent_certificates;
pub mod agent_metrics;
pub mod agents;
pub mod bootstrap_tokens;
pub mod bucket_access_keys;
pub mod buckets;
pub mod certificate_revocations;
pub mod failover_events;
pub mod garage_nodes;
pub mod identity_providers;
pub mod idp_group_mappings;
pub mod invalid_jwt;
pub mod key;
pub mod logs;
pub mod network_members;
pub mod network_policies;
pub mod networks;
pub mod oidc_exchange_codes;
pub mod oidc_login_states;
pub mod organization;
pub mod permission;
pub mod registry_tokens;
pub mod resource_group_vpn_peers;
pub mod resource_groups;
pub mod role;
pub mod role_permission;
pub mod system_settings;
pub mod user;
pub mod user_identities;
pub mod user_organization;
pub mod user_ssh_keys;
pub mod volume_snapshots;
pub mod volumes;
pub mod workload_stacks;
pub mod workloads;

pub use agent_api_keys::Entity as AgentApiKeys;
pub use agent_certificates::Entity as AgentCertificates;
pub use agent_metrics::Entity as AgentMetrics;
pub use agents::Entity as Agents;
pub use bootstrap_tokens::Entity as BootstrapTokens;
pub use bucket_access_keys::Entity as BucketAccessKeys;
pub use buckets::Entity as Buckets;
pub use certificate_revocations::Entity as CertificateRevocations;
pub use failover_events::Entity as FailoverEvents;
pub use garage_nodes::Entity as GarageNodes;
pub use identity_providers::Entity as IdentityProviders;
pub use idp_group_mappings::Entity as IdpGroupMappings;
pub use invalid_jwt::Entity as InvalidJwt;
pub use key::Entity as Key;
pub use logs::Entity as Logs;
pub use network_members::Entity as NetworkMembers;
pub use network_policies::Entity as NetworkPolicies;
pub use networks::Entity as Networks;
pub use oidc_exchange_codes::Entity as OidcExchangeCodes;
pub use oidc_login_states::Entity as OidcLoginStates;
pub use organization::Entity as Organization;
pub use permission::Entity as Permission;
pub use registry_tokens::Entity as RegistryTokens;
pub use resource_group_vpn_peers::Entity as ResourceGroupVpnPeers;
pub use resource_groups::Entity as ResourceGroups;
pub use role::Entity as Role;
pub use role_permission::Entity as RolePermission;
pub use system_settings::Entity as SystemSettings;
pub use user::Entity as User;
pub use user_identities::Entity as UserIdentities;
pub use user_organization::Entity as UserOrganization;
pub use user_ssh_keys::Entity as UserSshKeys;
pub use volume_snapshots::Entity as VolumeSnapshots;
pub use volumes::Entity as Volumes;
pub use workload_stacks::Entity as WorkloadStacks;
pub use workloads::Entity as Workloads;
